/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeCategory = { 'Senior' : null } |
  { 'Under12' : null } |
  { 'Under14' : null } |
  { 'Under16' : null } |
  { 'Under19' : null };
export interface Attendance {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : string,
}
export type AttendanceId = bigint;
export type AttendanceStatus = { 'Present' : null } |
  { 'Absent' : null };
export interface AttendanceSummaryEntry {
  'studentId' : StudentId,
  'studentName' : string,
  'totalDays' : bigint,
  'daysPresent' : bigint,
  'percentage' : bigint,
}
export type BatchTiming = { 'Morning' : null } |
  { 'Evening' : null };
export interface DashboardStats {
  'totalFeesCollected' : bigint,
  'totalStudents' : bigint,
  'feeOverdueCount' : bigint,
  'receiptsIssued' : bigint,
}
export type FeePaymentId = bigint;
export interface FeeStatusEntry {
  'student' : Student,
  'payment' : [] | [MonthlyFeePayment],
}
export interface MonthlyFeePayment {
  'id' : FeePaymentId,
  'month' : string,
  'studentId' : StudentId,
  'paymentDate' : string,
  'paymentMode' : PaymentMode,
  'amount' : bigint,
  'receiptNumber' : ReceiptNumber,
}
export interface MonthlyReport {
  'month' : string,
  'totalCollected' : bigint,
  'studentAttendanceSummary' : Array<AttendanceSummaryEntry>,
  'totalPending' : bigint,
}
export type PaymentMode = { 'Cash' : null } |
  { 'OnlineUPI' : null } |
  { 'Cheque' : null };
export type ReceiptNumber = string;
export interface Student {
  'id' : StudentId,
  'batchTiming' : BatchTiming,
  'name' : string,
  'photoUrl' : [] | [string],
  'totalPaid' : bigint,
  'whatsappNumber' : string,
  'locationId' : string,
  'paymentMode' : PaymentMode,
  'monthlyFees' : bigint,
  'registrationDate' : Timestamp,
  'registrationFees' : bigint,
  'guardianName' : string,
  'receiptNumber' : ReceiptNumber,
  'ageCategory' : AgeCategory,
}
export type StudentId = bigint;
export interface StudentInput {
  'batchTiming' : BatchTiming,
  'name' : string,
  'photoUrl' : [] | [string],
  'whatsappNumber' : string,
  'locationId' : string,
  'paymentMode' : PaymentMode,
  'monthlyFees' : bigint,
  'registrationFees' : bigint,
  'guardianName' : string,
  'ageCategory' : AgeCategory,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'changeAdminPin' : ActorMethod<[string, string, string], boolean>,
  'collectMonthlyFee' : ActorMethod<
    [StudentId, string, bigint, PaymentMode, string],
    ReceiptNumber
  >,
  'deleteStudent' : ActorMethod<
    [string, string, StudentId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAllMonthlyFeePayments' : ActorMethod<[string], Array<MonthlyFeePayment>>,
  'getAllStudents' : ActorMethod<[string], Array<Student>>,
  'getAttendanceByDate' : ActorMethod<[string, string], Array<Attendance>>,
  'getDashboardStats' : ActorMethod<[string], DashboardStats>,
  'getFeeStatusForMonth' : ActorMethod<[string, string], Array<FeeStatusEntry>>,
  'getLocations' : ActorMethod<[], Array<[string, string]>>,
  'getMonthlyFeePayments' : ActorMethod<[StudentId], Array<MonthlyFeePayment>>,
  'getMonthlyReport' : ActorMethod<[string, string], MonthlyReport>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudentAttendance' : ActorMethod<[StudentId], Array<Attendance>>,
  'getStudentByName' : ActorMethod<[string, string], Array<Student>>,
  'markAttendance' : ActorMethod<
    [StudentId, string, AttendanceStatus],
    boolean
  >,
  'registerStudent' : ActorMethod<[StudentInput], [StudentId, ReceiptNumber]>,
  'verifyAdminPin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];