/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudentId = IDL.Nat;
export const PaymentMode = IDL.Variant({
  'Cash' : IDL.Null,
  'OnlineUPI' : IDL.Null,
  'Cheque' : IDL.Null,
});
export const ReceiptNumber = IDL.Text;
export const FeePaymentId = IDL.Nat;
export const MonthlyFeePayment = IDL.Record({
  'id' : FeePaymentId,
  'month' : IDL.Text,
  'studentId' : StudentId,
  'paymentDate' : IDL.Text,
  'paymentMode' : PaymentMode,
  'amount' : IDL.Nat,
  'receiptNumber' : ReceiptNumber,
});
export const BatchTiming = IDL.Variant({
  'Morning' : IDL.Null,
  'Evening' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AgeCategory = IDL.Variant({
  'Senior' : IDL.Null,
  'Under12' : IDL.Null,
  'Under14' : IDL.Null,
  'Under16' : IDL.Null,
  'Under19' : IDL.Null,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'batchTiming' : BatchTiming,
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'totalPaid' : IDL.Nat,
  'whatsappNumber' : IDL.Text,
  'locationId' : IDL.Text,
  'paymentMode' : PaymentMode,
  'monthlyFees' : IDL.Nat,
  'registrationDate' : Timestamp,
  'registrationFees' : IDL.Nat,
  'guardianName' : IDL.Text,
  'receiptNumber' : ReceiptNumber,
  'ageCategory' : AgeCategory,
});
export const AttendanceId = IDL.Nat;
export const AttendanceStatus = IDL.Variant({
  'Present' : IDL.Null,
  'Absent' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalFeesCollected' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'feeOverdueCount' : IDL.Nat,
  'receiptsIssued' : IDL.Nat,
});
export const FeeStatusEntry = IDL.Record({
  'student' : Student,
  'payment' : IDL.Opt(MonthlyFeePayment),
});
export const AttendanceSummaryEntry = IDL.Record({
  'studentId' : StudentId,
  'studentName' : IDL.Text,
  'totalDays' : IDL.Nat,
  'daysPresent' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const MonthlyReport = IDL.Record({
  'month' : IDL.Text,
  'totalCollected' : IDL.Nat,
  'studentAttendanceSummary' : IDL.Vec(AttendanceSummaryEntry),
  'totalPending' : IDL.Nat,
});
export const StudentInput = IDL.Record({
  'batchTiming' : BatchTiming,
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'whatsappNumber' : IDL.Text,
  'locationId' : IDL.Text,
  'paymentMode' : PaymentMode,
  'monthlyFees' : IDL.Nat,
  'registrationFees' : IDL.Nat,
  'guardianName' : IDL.Text,
  'ageCategory' : AgeCategory,
});

export const idlService = IDL.Service({
  'changeAdminPin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'collectMonthlyFee' : IDL.Func(
      [StudentId, IDL.Text, IDL.Nat, PaymentMode, IDL.Text],
      [ReceiptNumber],
      [],
    ),
  'deleteStudent' : IDL.Func(
      [IDL.Text, IDL.Text, StudentId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAllMonthlyFeePayments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MonthlyFeePayment)],
      ['query'],
    ),
  'getAllStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
  'getFeeStatusForMonth' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(FeeStatusEntry)],
      ['query'],
    ),
  'getLocations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getMonthlyFeePayments' : IDL.Func(
      [StudentId],
      [IDL.Vec(MonthlyFeePayment)],
      ['query'],
    ),
  'getMonthlyReport' : IDL.Func(
      [IDL.Text, IDL.Text],
      [MonthlyReport],
      ['query'],
    ),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudentAttendance' : IDL.Func(
      [StudentId],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getStudentByName' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'markAttendance' : IDL.Func(
      [StudentId, IDL.Text, AttendanceStatus],
      [IDL.Bool],
      [],
    ),
  'registerStudent' : IDL.Func([StudentInput], [StudentId, ReceiptNumber], []),
  'verifyAdminPin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudentId = IDL.Nat;
  const PaymentMode = IDL.Variant({
    'Cash' : IDL.Null,
    'OnlineUPI' : IDL.Null,
    'Cheque' : IDL.Null,
  });
  const ReceiptNumber = IDL.Text;
  const FeePaymentId = IDL.Nat;
  const MonthlyFeePayment = IDL.Record({
    'id' : FeePaymentId,
    'month' : IDL.Text,
    'studentId' : StudentId,
    'paymentDate' : IDL.Text,
    'paymentMode' : PaymentMode,
    'amount' : IDL.Nat,
    'receiptNumber' : ReceiptNumber,
  });
  const BatchTiming = IDL.Variant({
    'Morning' : IDL.Null,
    'Evening' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const AgeCategory = IDL.Variant({
    'Senior' : IDL.Null,
    'Under12' : IDL.Null,
    'Under14' : IDL.Null,
    'Under16' : IDL.Null,
    'Under19' : IDL.Null,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'batchTiming' : BatchTiming,
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'totalPaid' : IDL.Nat,
    'whatsappNumber' : IDL.Text,
    'locationId' : IDL.Text,
    'paymentMode' : PaymentMode,
    'monthlyFees' : IDL.Nat,
    'registrationDate' : Timestamp,
    'registrationFees' : IDL.Nat,
    'guardianName' : IDL.Text,
    'receiptNumber' : ReceiptNumber,
    'ageCategory' : AgeCategory,
  });
  const AttendanceId = IDL.Nat;
  const AttendanceStatus = IDL.Variant({
    'Present' : IDL.Null,
    'Absent' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'studentId' : StudentId,
    'date' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalFeesCollected' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'feeOverdueCount' : IDL.Nat,
    'receiptsIssued' : IDL.Nat,
  });
  const FeeStatusEntry = IDL.Record({
    'student' : Student,
    'payment' : IDL.Opt(MonthlyFeePayment),
  });
  const AttendanceSummaryEntry = IDL.Record({
    'studentId' : StudentId,
    'studentName' : IDL.Text,
    'totalDays' : IDL.Nat,
    'daysPresent' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const MonthlyReport = IDL.Record({
    'month' : IDL.Text,
    'totalCollected' : IDL.Nat,
    'studentAttendanceSummary' : IDL.Vec(AttendanceSummaryEntry),
    'totalPending' : IDL.Nat,
  });
  const StudentInput = IDL.Record({
    'batchTiming' : BatchTiming,
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'whatsappNumber' : IDL.Text,
    'locationId' : IDL.Text,
    'paymentMode' : PaymentMode,
    'monthlyFees' : IDL.Nat,
    'registrationFees' : IDL.Nat,
    'guardianName' : IDL.Text,
    'ageCategory' : AgeCategory,
  });
  
  return IDL.Service({
    'changeAdminPin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'collectMonthlyFee' : IDL.Func(
        [StudentId, IDL.Text, IDL.Nat, PaymentMode, IDL.Text],
        [ReceiptNumber],
        [],
      ),
    'deleteStudent' : IDL.Func(
        [IDL.Text, IDL.Text, StudentId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAllMonthlyFeePayments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MonthlyFeePayment)],
        ['query'],
      ),
    'getAllStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
    'getFeeStatusForMonth' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(FeeStatusEntry)],
        ['query'],
      ),
    'getLocations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getMonthlyFeePayments' : IDL.Func(
        [StudentId],
        [IDL.Vec(MonthlyFeePayment)],
        ['query'],
      ),
    'getMonthlyReport' : IDL.Func(
        [IDL.Text, IDL.Text],
        [MonthlyReport],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudentAttendance' : IDL.Func(
        [StudentId],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getStudentByName' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'markAttendance' : IDL.Func(
        [StudentId, IDL.Text, AttendanceStatus],
        [IDL.Bool],
        [],
      ),
    'registerStudent' : IDL.Func(
        [StudentInput],
        [StudentId, ReceiptNumber],
        [],
      ),
    'verifyAdminPin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };