/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthlyReport {
    month: string;
    totalCollected: bigint;
    studentAttendanceSummary: Array<AttendanceSummaryEntry>;
    totalPending: bigint;
}
export type Timestamp = bigint;
export type ReceiptNumber = string;
export interface AttendanceSummaryEntry {
    studentId: StudentId;
    studentName: string;
    totalDays: bigint;
    daysPresent: bigint;
    percentage: bigint;
}
export type FeePaymentId = bigint;
export interface Attendance {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: string;
}
export interface StudentInput {
    batchTiming: BatchTiming;
    name: string;
    photoUrl?: string;
    whatsappNumber: string;
    locationId: string;
    paymentMode: PaymentMode;
    monthlyFees: bigint;
    registrationFees: bigint;
    guardianName: string;
    ageCategory: AgeCategory;
}
export type AttendanceId = bigint;
export interface DashboardStats {
    totalFeesCollected: bigint;
    totalStudents: bigint;
    feeOverdueCount: bigint;
    receiptsIssued: bigint;
}
export type StudentId = bigint;
export interface FeeStatusEntry {
    student: Student;
    payment?: MonthlyFeePayment;
}
export interface MonthlyFeePayment {
    id: FeePaymentId;
    month: string;
    studentId: StudentId;
    paymentDate: string;
    paymentMode: PaymentMode;
    amount: bigint;
    receiptNumber: ReceiptNumber;
}
export interface Student {
    id: StudentId;
    batchTiming: BatchTiming;
    name: string;
    photoUrl?: string;
    totalPaid: bigint;
    whatsappNumber: string;
    locationId: string;
    paymentMode: PaymentMode;
    monthlyFees: bigint;
    registrationDate: Timestamp;
    registrationFees: bigint;
    guardianName: string;
    receiptNumber: ReceiptNumber;
    ageCategory: AgeCategory;
}
export enum AgeCategory {
    Senior = "Senior",
    Under12 = "Under12",
    Under14 = "Under14",
    Under16 = "Under16",
    Under19 = "Under19"
}
export enum AttendanceStatus {
    Present = "Present",
    Absent = "Absent"
}
export enum BatchTiming {
    Morning = "Morning",
    Evening = "Evening"
}
export enum PaymentMode {
    Cash = "Cash",
    OnlineUPI = "OnlineUPI",
    Cheque = "Cheque"
}
export interface backendInterface {
    changeAdminPin(locationId: string, oldPin: string, newPin: string): Promise<boolean>;
    collectMonthlyFee(studentId: StudentId, month: string, amount: bigint, paymentMode: PaymentMode, paymentDate: string): Promise<ReceiptNumber>;
    deleteStudent(locationId: string, adminPin: string, studentId: StudentId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllMonthlyFeePayments(locationId: string): Promise<Array<MonthlyFeePayment>>;
    getAllStudents(locationId: string): Promise<Array<Student>>;
    getAttendanceByDate(locationId: string, date: string): Promise<Array<Attendance>>;
    getDashboardStats(locationId: string): Promise<DashboardStats>;
    getFeeStatusForMonth(locationId: string, month: string): Promise<Array<FeeStatusEntry>>;
    getLocations(): Promise<Array<[string, string]>>;
    getMonthlyFeePayments(studentId: StudentId): Promise<Array<MonthlyFeePayment>>;
    getMonthlyReport(locationId: string, month: string): Promise<MonthlyReport>;
    getStudent(id: StudentId): Promise<Student | null>;
    getStudentAttendance(studentId: StudentId): Promise<Array<Attendance>>;
    getStudentByName(locationId: string, name: string): Promise<Array<Student>>;
    markAttendance(studentId: StudentId, date: string, status: AttendanceStatus): Promise<boolean>;
    registerStudent(data: StudentInput): Promise<[StudentId, ReceiptNumber]>;
    verifyAdminPin(locationId: string, pin: string): Promise<boolean>;
}
import type { AgeCategory as _AgeCategory, Attendance as _Attendance, AttendanceId as _AttendanceId, AttendanceStatus as _AttendanceStatus, BatchTiming as _BatchTiming, FeePaymentId as _FeePaymentId, FeeStatusEntry as _FeeStatusEntry, MonthlyFeePayment as _MonthlyFeePayment, PaymentMode as _PaymentMode, ReceiptNumber as _ReceiptNumber, Student as _Student, StudentId as _StudentId, StudentInput as _StudentInput, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async changeAdminPin(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPin(arg0, arg1, arg2);
            return result;
        }
    }
    async collectMonthlyFee(arg0: StudentId, arg1: string, arg2: bigint, arg3: PaymentMode, arg4: string): Promise<ReceiptNumber> {
        if (this.processError) {
            try {
                const result = await this.actor.collectMonthlyFee(arg0, arg1, arg2, to_candid_PaymentMode_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.collectMonthlyFee(arg0, arg1, arg2, to_candid_PaymentMode_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async deleteStudent(arg0: string, arg1: string, arg2: StudentId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMonthlyFeePayments(arg0: string): Promise<Array<MonthlyFeePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMonthlyFeePayments(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMonthlyFeePayments(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByDate(arg0: string, arg1: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByDate(arg0, arg1);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByDate(arg0, arg1);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(arg0: string): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats(arg0);
            return result;
        }
    }
    async getFeeStatusForMonth(arg0: string, arg1: string): Promise<Array<FeeStatusEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStatusForMonth(arg0, arg1);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStatusForMonth(arg0, arg1);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocations(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocations();
            return result;
        }
    }
    async getMonthlyFeePayments(arg0: StudentId): Promise<Array<MonthlyFeePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyFeePayments(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyFeePayments(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyReport(arg0: string, arg1: string): Promise<MonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReport(arg0, arg1);
            return result;
        }
    }
    async getStudent(arg0: StudentId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAttendance(arg0: StudentId): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAttendance(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAttendance(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentByName(arg0: string, arg1: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentByName(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentByName(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAttendance(arg0: StudentId, arg1: string, arg2: AttendanceStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n27(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n27(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async registerStudent(arg0: StudentInput): Promise<[StudentId, ReceiptNumber]> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(to_candid_StudentInput_n29(this._uploadFile, this._downloadFile, arg0));
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(to_candid_StudentInput_n29(this._uploadFile, this._downloadFile, arg0));
            return [
                result[0],
                result[1]
            ];
        }
    }
    async verifyAdminPin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AgeCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgeCategory): AgeCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Attendance_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_BatchTiming_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchTiming): BatchTiming {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FeeStatusEntry_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeStatusEntry): FeeStatusEntry {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_MonthlyFeePayment_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MonthlyFeePayment): MonthlyFeePayment {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonthlyFeePayment]): MonthlyFeePayment | null {
    return value.length === 0 ? null : from_candid_MonthlyFeePayment_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    batchTiming: _BatchTiming;
    name: string;
    photoUrl: [] | [string];
    totalPaid: bigint;
    whatsappNumber: string;
    locationId: string;
    paymentMode: _PaymentMode;
    monthlyFees: bigint;
    registrationDate: _Timestamp;
    registrationFees: bigint;
    guardianName: string;
    receiptNumber: _ReceiptNumber;
    ageCategory: _AgeCategory;
}): {
    id: StudentId;
    batchTiming: BatchTiming;
    name: string;
    photoUrl?: string;
    totalPaid: bigint;
    whatsappNumber: string;
    locationId: string;
    paymentMode: PaymentMode;
    monthlyFees: bigint;
    registrationDate: Timestamp;
    registrationFees: bigint;
    guardianName: string;
    receiptNumber: ReceiptNumber;
    ageCategory: AgeCategory;
} {
    return {
        id: value.id,
        batchTiming: from_candid_BatchTiming_n12(_uploadFile, _downloadFile, value.batchTiming),
        name: value.name,
        photoUrl: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.photoUrl)),
        totalPaid: value.totalPaid,
        whatsappNumber: value.whatsappNumber,
        locationId: value.locationId,
        paymentMode: from_candid_PaymentMode_n7(_uploadFile, _downloadFile, value.paymentMode),
        monthlyFees: value.monthlyFees,
        registrationDate: value.registrationDate,
        registrationFees: value.registrationFees,
        guardianName: value.guardianName,
        receiptNumber: value.receiptNumber,
        ageCategory: from_candid_AgeCategory_n15(_uploadFile, _downloadFile, value.ageCategory)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    status: _AttendanceStatus;
    studentId: _StudentId;
    date: string;
}): {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: string;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n20(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    student: _Student;
    payment: [] | [_MonthlyFeePayment];
}): {
    student: Student;
    payment?: MonthlyFeePayment;
} {
    return {
        student: from_candid_Student_n10(_uploadFile, _downloadFile, value.student),
        payment: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.payment))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FeePaymentId;
    month: string;
    studentId: _StudentId;
    paymentDate: string;
    paymentMode: _PaymentMode;
    amount: bigint;
    receiptNumber: _ReceiptNumber;
}): {
    id: FeePaymentId;
    month: string;
    studentId: StudentId;
    paymentDate: string;
    paymentMode: PaymentMode;
    amount: bigint;
    receiptNumber: ReceiptNumber;
} {
    return {
        id: value.id,
        month: value.month,
        studentId: value.studentId,
        paymentDate: value.paymentDate,
        paymentMode: from_candid_PaymentMode_n7(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount,
        receiptNumber: value.receiptNumber
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Morning: null;
} | {
    Evening: null;
}): BatchTiming {
    return "Morning" in value ? BatchTiming.Morning : "Evening" in value ? BatchTiming.Evening : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Senior: null;
} | {
    Under12: null;
} | {
    Under14: null;
} | {
    Under16: null;
} | {
    Under19: null;
}): AgeCategory {
    return "Senior" in value ? AgeCategory.Senior : "Under12" in value ? AgeCategory.Under12 : "Under14" in value ? AgeCategory.Under14 : "Under16" in value ? AgeCategory.Under16 : "Under19" in value ? AgeCategory.Under19 : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Present: null;
} | {
    Absent: null;
}): AttendanceStatus {
    return "Present" in value ? AttendanceStatus.Present : "Absent" in value ? AttendanceStatus.Absent : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Cash: null;
} | {
    OnlineUPI: null;
} | {
    Cheque: null;
}): PaymentMode {
    return "Cash" in value ? PaymentMode.Cash : "OnlineUPI" in value ? PaymentMode.OnlineUPI : "Cheque" in value ? PaymentMode.Cheque : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendance>): Array<Attendance> {
    return value.map((x)=>from_candid_Attendance_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeStatusEntry>): Array<FeeStatusEntry> {
    return value.map((x)=>from_candid_FeeStatusEntry_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MonthlyFeePayment>): Array<MonthlyFeePayment> {
    return value.map((x)=>from_candid_MonthlyFeePayment_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AgeCategory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeCategory): _AgeCategory {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_BatchTiming_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchTiming): _BatchTiming {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_StudentInput_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentInput): _StudentInput {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    batchTiming: BatchTiming;
    name: string;
    photoUrl?: string;
    whatsappNumber: string;
    locationId: string;
    paymentMode: PaymentMode;
    monthlyFees: bigint;
    registrationFees: bigint;
    guardianName: string;
    ageCategory: AgeCategory;
}): {
    batchTiming: _BatchTiming;
    name: string;
    photoUrl: [] | [string];
    whatsappNumber: string;
    locationId: string;
    paymentMode: _PaymentMode;
    monthlyFees: bigint;
    registrationFees: bigint;
    guardianName: string;
    ageCategory: _AgeCategory;
} {
    return {
        batchTiming: to_candid_BatchTiming_n31(_uploadFile, _downloadFile, value.batchTiming),
        name: value.name,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        whatsappNumber: value.whatsappNumber,
        locationId: value.locationId,
        paymentMode: to_candid_PaymentMode_n1(_uploadFile, _downloadFile, value.paymentMode),
        monthlyFees: value.monthlyFees,
        registrationFees: value.registrationFees,
        guardianName: value.guardianName,
        ageCategory: to_candid_AgeCategory_n33(_uploadFile, _downloadFile, value.ageCategory)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    Cash: null;
} | {
    OnlineUPI: null;
} | {
    Cheque: null;
} {
    return value == PaymentMode.Cash ? {
        Cash: null
    } : value == PaymentMode.OnlineUPI ? {
        OnlineUPI: null
    } : value == PaymentMode.Cheque ? {
        Cheque: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    Present: null;
} | {
    Absent: null;
} {
    return value == AttendanceStatus.Present ? {
        Present: null
    } : value == AttendanceStatus.Absent ? {
        Absent: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchTiming): {
    Morning: null;
} | {
    Evening: null;
} {
    return value == BatchTiming.Morning ? {
        Morning: null
    } : value == BatchTiming.Evening ? {
        Evening: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeCategory): {
    Senior: null;
} | {
    Under12: null;
} | {
    Under14: null;
} | {
    Under16: null;
} | {
    Under19: null;
} {
    return value == AgeCategory.Senior ? {
        Senior: null
    } : value == AgeCategory.Under12 ? {
        Under12: null
    } : value == AgeCategory.Under14 ? {
        Under14: null
    } : value == AgeCategory.Under16 ? {
        Under16: null
    } : value == AgeCategory.Under19 ? {
        Under19: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
